source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NKJMultiMovieCaptureView_Example', :exclusive => true do
  pod "NKJMultiMovieCaptureView", :path => "../"
end

target 'NKJMultiMovieCaptureView_Tests', :exclusive => true do
  pod "NKJMultiMovieCaptureView", :path => "../"

  
end
